<?php
/*
@name: dwz-shorturl Asset Builder
@description: 零依赖静态资源构建：压缩 assets 下的 CSS/JS 并注入内容哈希版本号。

用法：
  php migrations/build_assets.php            # 构建（写入 assets/*.min.css|min.js）
  php migrations/build_assets.php --check    # 只校验版本号是否为最新（CI 用，不写文件）

设计取舍：项目主打「依赖少、部署方便」，因此这里不引入 npm/esbuild 工具链，
用纯 PHP 做保守的压缩（去注释、折叠空白），并输出 app.min.css / app.min.js。
HTML 中的引用改为通过 ?v=<hash> 表达，改内容即改版本，避免手工维护版本号漂移。
*/
if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit("CLI only\n");
}

$root = dirname(__DIR__);
$assetsDir = $root . '/assets';

// 需要构建的源文件 => 产物名
$targets = array(
    'tokens.css' => 'tokens.min.css',
    'app.css'    => 'app.min.css',
    'app.js'     => 'app.min.js',
);

$checkOnly = in_array('--check', $argv, true);
$options = array();

// 保守压缩 CSS：移除注释（保留 /*! 版权注释）、折叠空白、去掉行尾分号前空格。
function minify_css($css) {
    $css = preg_replace('#/\*(?!!)[^*]*\*+(?:[^/*][^*]*\*+)*/#', '', $css);
    $css = preg_replace('/\s+/', ' ', $css);
    $css = preg_replace('/\s*([{}:;,>~+])\s*/', '$1', $css);
    $css = preg_replace('/;}/', '}', $css);
    return trim($css);
}

// 保守压缩 JS：状态机删除注释并折叠空白，正确处理字符串/模板串与
// 正则字面量（正则里的 // 不能被误判为行注释）。不改变 token 语义，
// 换行仅在原位置是换行时才保留，避免触发 ASI 问题。
function minify_js($js) {
    $len = strlen($js);
    $out = '';
    $i = 0;
    // 上一个有意义的字符，用于判定 '/' 是除号还是正则起始。
    $prev = '';
    $regexAllowedAfter = array('', '(', ',', '=', ':', '[', '!', '&', '|', '?', '{', '}', ';', '+', '-', '*', '%', '~', '^', '<', '>', "\n");

    while ($i < $len) {
        $c = $js[$i];
        $n = $i + 1 < $len ? $js[$i + 1] : '';

        // 行注释
        if ($c === '/' && $n === '/') {
            while ($i < $len && $js[$i] !== "\n") $i++;
            continue;
        }
        // 块注释（保留 /*! 版权注释）
        if ($c === '/' && $n === '*') {
            $keep = ($i + 2 < $len && $js[$i + 2] === '!');
            $end = strpos($js, '*/', $i + 2);
            if ($end === false) break;
            if ($keep) { $out .= substr($js, $i, $end + 2 - $i); $prev = '/'; }
            $i = $end + 2;
            continue;
        }
        // 正则字面量：仅当上一个 token 允许正则时才按正则解析。
        if ($c === '/' && in_array($prev, $regexAllowedAfter, true)) {
            $out .= $c;
            $i++;
            $inClass = false;
            while ($i < $len) {
                $ch = $js[$i];
                $out .= $ch;
                if ($ch === '\\') { $i++; if ($i < $len) { $out .= $js[$i]; } $i++; continue; }
                if ($ch === '[') $inClass = true;
                elseif ($ch === ']') $inClass = false;
                elseif ($ch === '/' && !$inClass) { $i++; break; }
                $i++;
            }
            // 正则 flag
            while ($i < $len && preg_match('/[a-z]/i', $js[$i])) { $out .= $js[$i]; $i++; }
            $prev = '/';
            continue;
        }
        // 字符串 / 模板串
        if ($c === '"' || $c === "'" || $c === '`') {
            $quote = $c;
            $out .= $c;
            $i++;
            while ($i < $len) {
                $ch = $js[$i];
                $out .= $ch;
                if ($ch === '\\') { $i++; if ($i < $len) { $out .= $js[$i]; } $i++; continue; }
                if ($ch === $quote) { $i++; break; }
                $i++;
            }
            $prev = $quote;
            continue;
        }
        // 折叠空白（保留换行，规避 ASI 风险）
        if ($c === ' ' || $c === "\t" || $c === "\r" || $c === "\n") {
            $j = $i;
            $sawNewline = false;
            while ($j < $len && in_array($js[$j], array(' ', "\t", "\r", "\n"), true)) {
                if ($js[$j] === "\n") $sawNewline = true;
                $j++;
            }
            $out .= $sawNewline ? "\n" : ' ';
            $i = $j;
            continue;
        }
        $out .= $c;
        $prev = $c;
        $i++;
    }
    $out = preg_replace("/\n{2,}/", "\n", $out);
    return trim($out);
}

$changed = false;
foreach ($targets as $src => $dest) {
    $srcPath = $assetsDir . '/' . $src;
    if (!is_file($srcPath)) {
        fwrite(STDERR, "missing source: {$src}\n");
        exit(1);
    }
    $code = file_get_contents($srcPath);
    $min = substr($src, -3) === '.js' ? minify_js($code) : minify_css($code);
    $hash = substr(sha1($min), 0, 8);
    $options[$src] = $hash;
    $destPath = $assetsDir . '/' . $dest;
    // 产物 = banner + 压缩正文；--check 必须与完整产物比对（含 banner），
    // 否则会永远报告 stale。
    $banner = "/* {$src} @{$hash} - generated by migrations/build_assets.php, do not edit */\n";
    $expected = $banner . $min;

    if ($checkOnly) {
        $current = is_file($destPath) ? file_get_contents($destPath) : '';
        if ($current !== $expected) {
            fwrite(STDERR, "stale: {$dest} (run: php migrations/build_assets.php)\n");
            exit(1);
        }
        continue;
    }

    file_put_contents($destPath, $expected);
    $saved = strlen($code) - strlen($min);
    fwrite(STDOUT, sprintf("%-12s -> %-16s %6d -> %6d bytes (v=%s)\n", $src, $dest, strlen($code), strlen($min), $hash));
    $changed = true;
}

if ($checkOnly) {
    fwrite(STDOUT, "assets up to date\n");
    exit(0);
}

// 把产物引用与内容哈希版本注入静态页面，彻底消除手工维护的 ?v=x.y.z 漂移。
// 只替换 assets 引用，其他内容原样保留。
$htmlFiles = array('index.html', 'api.html', 'stats.php');
foreach ($htmlFiles as $htmlFile) {
    $htmlPath = $root . '/' . $htmlFile;
    if (!is_file($htmlPath)) continue;
    $html = file_get_contents($htmlPath);
    $original = $html;
    // tokens.css / app.css -> 压缩版，并带上各自的哈希版本
    $html = preg_replace('~\./assets/tokens\.css(?:\?v=[^"\']*)?~', './assets/tokens.min.css?v=' . $options['tokens.css'], $html);
    $html = preg_replace('~\./assets/app\.css(?:\?v=[^"\']*)?~', './assets/app.min.css?v=' . $options['app.css'], $html);
    $html = preg_replace('~\./assets/app\.js(?:\?v=[^"\']*)?~', './assets/app.min.js?v=' . $options['app.js'], $html);
    if ($html !== $original) {
        file_put_contents($htmlPath, $html);
        fwrite(STDOUT, "versioned: {$htmlFile}\n");
    }
}

// 可选：把版本号写入 assets/manifest.json，供服务端模板读取。
file_put_contents($assetsDir . '/manifest.json', json_encode(array(
    'generated_at' => date('c'),
    'versions' => $options,
), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
fwrite(STDOUT, "manifest written: assets/manifest.json\n");
